### ISSUE TITLE
Invalid constructor of PaymentRequestPaymentData

### ISSUE THREAD

**Issue by varche1** [cardpay/python-sdk-v3#1]
Documentation says about `authentication_request ` as 
```
If set to true, amount must not be presented in request, no payment will be made, only cardholder authentication will be performed.
Also can be used to generate token.
```

But I can't create new `PaymentRequestPaymentData` without amout
```
>>> PaymentRequestPaymentData(currency="EUR", generate_token=True, authentication_request=True)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/cardpay/model/payment_request_payment_data.py", line 82, in __init__
    self.amount = amount
  File "/usr/local/lib/python3.7/site-packages/cardpay/model/payment_request_payment_data.py", line 121, in amount
    "Invalid value for `amount`, must not be `None`"
ValueError: Invalid value for `amount`, must not be `None`
```

Setting `amount` is not the solution, because API refuses such request:

```
{
    "name": "INVALID_API_REQUEST",
    "message": "Errors: [fields ['payment_data.amount'] not expected in authentication request]"
}
```

**Comment by varche1** [comment]
Now it works, but only for creating request. It fails when process callback data
```
File "/usr/local/lib/python3.7/site-packages/cardpay/api_client.py", line 899, in process
    obj = self.client.parse_callback(message)
  File "/usr/local/lib/python3.7/site-packages/cardpay/api_client.py", line 157, in parse_callback
    return self.from_json(message, PaymentCallback)
  File "/usr/local/lib/python3.7/site-packages/cardpay/api_client.py", line 141, in from_json
    return self.__deserialize(data, data_type)
  File "/usr/local/lib/python3.7/site-packages/cardpay/api_client.py", line 378, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/cardpay/api_client.py", line 760, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/local/lib/python3.7/site-packages/cardpay/api_client.py", line 378, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/local/lib/python3.7/site-packages/cardpay/api_client.py", line 762, in __deserialize_model
    instance = klass(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/cardpay/model/payment_response_payment_data.py", line 94, in __init__
    self.amount = amount
  File "/usr/local/lib/python3.7/site-packages/cardpay/model/payment_response_payment_data.py", line 138, in amount
    "Invalid value for `amount`, must not be `None`"
ValueError: Invalid value for `amount`, must not be `None`
```

**Comment by varche1** [comment]
Works now!
